### ISSUE TITLE
stress and interbench: huge utilization of cpu/memory causing hung_task_timeout and OOM call trace messages

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#329]
perf/stress.py
generic/intrebench

These testcases creates a huge stress on the machine, making the test hung and test never completes.
report is not being generated.

Handle it in testcase to kill the pid for never ending testcases.

**Comment by PraveenPenguin** [comment]
@harish-24 if possible  can you please have a look on 
`perf/stress.py`  i will take a look on` generic/intrebench` ?

**Comment by apahim** [comment]
From http://people.seas.harvard.edu/~apw/stress/FAQ:
>make sure you understand how much memory you have and then pass the appropriate options

**Question:** did you pass the appropriate options for your system?

---

From http://ck.kolivas.org/apps/interbench/readme:
>Simulating heavy memory and swap pressure by repeatedly accessing 110% of
available ram and moving it around and freeing it. You need to have some
swap enabled due to the nature of this load, and if it detects no swap this
load is disabled.

**Question:** Do you have enough swap to have a single process consuming 110% of your RAM and still keep the rest of processes away from the oom-killer hunger?

**Comment by apahim** [comment]
> These testcases creates a huge stress on the machine

Aren't they meant for that? Question is: can your machine survive? :)

**Comment by PraveenPenguin** [comment]
@abdhaleegit can you please help us to understand more about this issue as @apahim asked like system resources ?

**Comment by PraveenPenguin** [comment]
@abdhaleegit still you want to pursue this ?

**Comment by PraveenPenguin** [comment]
closing this is as there is no response from author @abdhaleegit if you still want to pursue this feel free to reopen this
