### ISSUE TITLE
lib/utility script to have basic functions for IBM tools (hmc, ipmi, fsp, phyp, vios)

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework-tests/avocado-misc-tests#971]
Hi 

Many misc test cases like DLPAR, virt-net, and going forward most of the IBM Power specific testcases make use of basic functions from tools like hmc, ipmi, fsp, phyp, vios

@ldoktor @apahim @narasimhan-v @PraveenPenguin how about having a utility script in avocado-misc-test ? which contains library functions to cover the basic functions to interact with hmc, ipmi, fsp, phyp, vios

Please suggest if there are any more better ways to handle this

**Comment by narasimhan-v** [comment]
I can think of only these 2 posibilities:
1. add an avocado util
2. location for util / scripts in avocado-misc-tests

Will let @ldoktor @apahim give their views.

**Comment by ldoktor** [comment]
Hello guys, I'd really encourage you to sent the generic utils to `avocado.utils`, because `avocado-misc-tests` is not the only place tests are being developed. Sharing it there would allow eg. avocado-vt or other projects to re-use them and more importantly to refine and improve them.

On the other hand if you have something really specific, you should put it into a shared location within this repo, but I guess there should not be many of these (maybe some shared setups or so). But this should be really limited and most stuff should go to `avocado`.

CC: @clebergnu

**Comment by PraveenPenguin** [comment]
@abdhaleegit yes i agree with @narasimhan-v and @ldoktor this should be part of avocado lib under  
avocado.utils 
as example can be 
`avocado.utils .phyp'
